info:
  name: Use inventory item
  type: http
  seq: 3

http:
  method: POST
  url: "http://localhost:8090/koi_breeding/api/v1/inventory/items/:itemId/usages?userId=1"
  params:
    - name: itemId
      value: "1"
      type: path
  body:
    type: json
    data: |-
      {"quantity": 1}
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
