server:
    port: 8090
    servlet:
        context-path: /koi_breeding

spring:
    application:
        name: koi-breeding

    profiles:
        active: local

    datasource:
        url: jdbc:postgresql://localhost:5432/koi_breeding

    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

        properties:
            hibernate:
                default_schema: koi_breeding

        show-sql: true
