package com.koibreeding.seeder;

import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import com.koibreeding.domain.Variety;
import com.koibreeding.repository.VarietyRepository;

@Component
@Order(1)
public class VarietySeeder implements CommandLineRunner {
    private final VarietyRepository varietyRepository;

    public VarietySeeder(VarietyRepository varietyRepository) {
        this.varietyRepository = varietyRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        if (varietyRepository.count() > 0) {
            System.out.println(">>> Varieties already exist");
            return;
        }

        varietyRepository.saveAll(SAMPLE_VARIETIES);
        System.out.println(">>> Seeded Varieties Successfully");
    }

    private static final List<Variety> SAMPLE_VARIETIES = List.of(
            new Variety(null, "Kohaku", // 0
                    "Cá Koi Kohaku là giống cá Koi nổi tiếng và phổ biến nhất, dễ nhận diện nhờ sự kết hợp hài hòa giữa nền trắng tinh khôi và các mảng đỏ rực rỡ. Đây là dòng Wagoi (có vảy), với vảy ánh bạc đều đặn, tạo nên vẻ đẹp sang trọng và tinh tế.\nMột Kohaku đẹp phải có thân hình thon dài, chắc khỏe, dáng giọt nước cân đối; vây trắng tuyết dày, căng tròn, không dính đỏ; vảy đều và sáng bóng. Nền trắng phải sạch sẽ, không có đốm đen hay xỉn màu, trong khi màu đỏ đậm như ớt chín, đồng đều từ đầu đến đuôi.\nHọa tiết trên đầu không phủ qua mắt và miệng, dừng lại cách mũi một khoảng trắng (Odome), họa tiết trên thân cân đối hai bên và không chạm vào gốc đuôi, cách ít nhất 2cm để tránh lỗi thẩm mỹ Shimizushi. Kohaku được xem là “nền tảng” của nghệ thuật nuôi cá Koi, mang vẻ đẹp thanh tao nhưng mạnh mẽ, và luôn giữ vị trí đặc biệt trong mọi bộ sưu tập Koi."),
            new Variety(null, "Tancho", // 1
                    "Cá Koi Tancho là giống cá đặc biệt và hiếm, nổi bật với chấm đỏ tròn đều nằm chính giữa đầu, cân đối giữa hai mắt. Thân cá có nền trắng tinh khiết (Shiroji), không lẫn đốm đen hay vết lem, kết hợp với chấm đỏ (Hi) rực rỡ, đậm màu như ớt chín.\nTancho đẹp phải có thân hình khỏe mạnh, thuôn dài, vây trắng tuyết dày và đối xứng, không dính đỏ hay tia máu. Dáng bơi thẳng, uyển chuyển, nhẹ nhàng, toát lên vẻ quý phái.\nĐây là giống cá mang ý nghĩa may mắn và thịnh vượng, đặc biệt được yêu thích tại Nhật Bản vì chấm đỏ trên đầu gợi liên tưởng đến quốc kỳ. Một Tancho chuẩn mực là sự kết hợp hoàn hảo giữa chấm đỏ cân đối, nền trắng tinh khôi và dáng bơi thanh thoát, tạo nên giá trị cao trong bộ sưu tập Koi."),
            new Variety(null, "Taisho Sanke", // 2
                    "Cá Koi Taisho Sanke là giống cá phát triển từ Kohaku, nổi bật với nền trắng tinh khiết kết hợp các mảng đỏ rực rỡ và những chấm đen nhỏ sắc nét rải rác trên thân. Đây là dòng Wagoi (có vảy), mang vẻ đẹp thanh thoát và cân đối.\\nMột Sanke đẹp phải có nền trắng chiếm khoảng 50–60% diện tích, sạch sẽ nnhư men sứ; mảng đỏ chiếm 30–40%, đỏ đậm, bóng mịn với ranh giới sắc nét; chấm đen chiếm 10–20%, nhỏ gọn, bóng như mực tàu và rải đều từ vai đến đuôi. Đầu cá tuyệt đối không có màu đen, chỉ có trắng và đỏ, trong khi vây ngực lý tưởng có 2–3 tia sọc đen thẳng, vây trắng hoàn toàn cũng được chấp nhận.\\nThân hình Sanke to khỏe, vai rộng, lưng dày, dáng thuôn dài như thủy lôi, kết hợp với dáng bơi uyển chuyển, đuôi vẫy mạnh mẽ nhưng thân không lắc lư. Sự cân bằng hoàn hảo giữa ba màu trắng, đỏ và đen tạo nên vẻ đẹp sang trọng, thanh thoát và giá trị cao trong bộ sưu tập Koi."),
            new Variety(null, "Showa Sanshoku", // 3
                    "Cá Koi Showa Sanshoku là một trong ba giống Koi kinh điển, nổi bật với nền da đen chiếm đa số kết hợp hài hòa cùng các mảng trắng tinh khiết và đỏ rực rỡ. Đây là dòng Wagoi (có vảy), mang vẻ đẹp mạnh mẽ, uy nghi và đầy quyền lực.\\nMột Showa đẹp phải có các mảng đen to rộng, sâu và bóng bẩy như mực tàu, chạy loang vệt mạnh mẽ quanh thân và vệt đen lớn trên đầu tạo hình chữ Y hoặc X, đem lại vẻ dữ dằn đặc trưng. Vây ngực có Motoguro đối xứng, chiếm khoảng một phần ba diện tích vây, phần còn lại trắng sạch sẽ. Màu đỏ phải đậm như máu hoặc ớt chín, phân bổ thành khối lớn đối xứng, trong khi nền trắng muốt như men sứ giúp cân bằng tổng thể.\\nThân hình Showa to khỏe, vai rộng, lưng dày, dáng thuôn dài như quả thủy lôi, có tiềm năng phát triển kích thước vượt trội trên 85–90cm. Dáng bơi uyển chuyển nhưng mạnh mẽ, đuôi vẫy dứt khoát, thân không lắc lư. Sự hòa quyện hoàn hảo của ba màu đen, đỏ, trắng cùng thể hình khổng lồ khiến Showa Sanshoku trở thành biểu tượng sức mạnh và viên ngọc quý trong bộ sưu tập Koi."),
            new Variety(null, "Goromo", // 4
                    "Cá Koi Goromo là giống cá được lai chéo giữa Kohaku và Asagi, mang vẻ đẹp độc đáo và hiếm có. Nền da trắng tuyết hoặc trắng sữa tinh khiết, không pha vàng hay nhạt màu, kết hợp với các mảng đỏ thẫm đồng đều. \\nĐiểm đặc biệt của Goromo là đường viền quanh các mảng đỏ có màu xanh Indigo hoặc đen, tạo hoa văn dạng lưới như tổ ong, khiến cá trở nên nổi bật và khác biệt. Phần đầu cá càng ít mảng màu hoặc sạch sẽ không tỳ vết thì giá trị càng cao.\\nNgoài ra, các tiêu chí đánh giá khác cũng tương tự như những dòng Koi truyền thống, chú trọng vào sự cân đối của thể hình, màu sắc và dáng bơi. Goromo mang lại vẻ đẹp thanh tao nhưng vẫn mạnh mẽ, là sự kết hợp hoàn hảo giữa sự tinh khiết của Kohaku và nét huyền bí của Asagi."),
            new Variety(null, "Utsuri", // 5
                    "Cá Koi Utsuri là dòng cá nổi bật với sự tương phản mạnh mẽ giữa màu đen tuyền sâu thẳm và một màu thứ hai như trắng, đỏ hoặc vàng. Trong đó, Shiro Utsuri truyền thống có thân đen trắng như tranh thủy mặc, còn Hi Utsuri và Ki Utsuri mang sắc đỏ hoặc vàng rực rỡ trên nền đen. Màu đen (Sumi) phải bóng bẩy như mực tàu, phân bổ thành mảng lớn, dày dặn và nổi khối nhẹ trên da, trong khi màu trắng, đỏ hoặc vàng phải tinh khiết, đậm và đồng đều.\\nHọa tiết của Utsuri thường đan xen như quân cờ hoặc chạy zigzag dọc thân, tạo sự cân đối hai bên, với vệt đen lớn trên đầu hình chữ Y hoặc X làm tăng vẻ uy nghi. Vây ngực có Motoguro đối xứng, phần còn lại sạch sẽ, là điểm nhấn đặc trưng nâng cao giá trị cá. Thân hình Utsuri to khỏe, đầu rộng, vai dày, dáng thuôn dài như thủy lôi, có tiềm năng phát triển trên 80–85cm.\\nDáng bơi uyển chuyển nhưng đầy quyền lực, đuôi vẫy mạnh mẽ mà thân không lắc lư, khiến Utsuri trở thành một trong những dòng cá Koi mang vẻ đẹp nghệ thuật và giá trị cao nhất."),
            new Variety(null, "Hikari Utsuri", // 6
                    "Cá Koi Hikari Utsuri là nhánh nhỏ của dòng Utsuri và cũng là loại Koi kim loại đầu tiên phát triển từ Showa, đặc trưng bởi lớp vảy óng ánh kim rực rỡ.\\nĐây là dòng Wagoi (có vảy), được đánh giá chủ yếu dựa trên độ sáng bóng và óng ánh của lớp vảy kim loại, càng lấp lánh thì giá trị càng cao. Các tiêu chí khác vẫn dựa theo chuẩn của Utsuri, với sự cân đối giữa màu đen tuyền sâu thẳm và màu sắc thứ hai.\\nHikari Utsuri có ba biến thể chính: Hikari Shiro Utsuri với màu trắng đen truyền thống, Hi Utsuri với màu đỏ đen nổi bật, và Ki Utsuri với màu vàng đen hiếm gặp. Sự kết hợp giữa ánh kim độc đáo và họa tiết mạnh mẽ khiến Hikari Utsuri trở thành một trong những dòng Koi ấn tượng và giá trị cao trong bộ sưu tập."),
            new Variety(null, "Bekko", // 7
                    "Cá Koi Bekko là dòng cá mang vẻ đẹp giản dị nhưng tinh tế, dễ nhận diện nhờ sự kết hợp giữa màu nền trắng, đỏ hoặc vàng với những đốm đen nhỏ rải rác phía trên đường bên.\\nKhác với Utsuri, hoa văn đen của Bekko nhỏ gọn, sắc nét và thường không xuất hiện trên đầu, mà phân bố dọc thân cá, so le hai bên vây lưng tạo sự cân đối. Đây là dòng Wagoi (có vảy), với vảy đục không ánh kim, mắt to, thân trong, vai và bụng tròn bầu hơn cá thường. Bekko đẹp phải có nền màu tinh khiết, đốm đen rõ ràng, không loang lổ, và hoa văn phân bổ hài hòa.\\nDòng này có ba biến thể chính: Shiro Bekko (trắng – đen), Aka Bekko (đỏ – đen), và Ki Bekko (vàng – đen). Sự đơn giản nhưng thanh thoát trong màu sắc và họa tiết khiến Bekko trở thành một trong những giống Koi được yêu thích, mang lại vẻ đẹp nhẹ nhàng và giá trị thẩm mỹ cao trong bộ sưu tập."),
            new Variety(null, "Karashi", // 8
                    "Cá Koi Karashi là giống cá đơn sắc thuộc nhóm Kawarimono, nổi bật với toàn thân màu vàng nhạt đến vàng đậm tươi sáng, đồng đều từ đầu đến đuôi. Đây là dòng Wagoi (có vảy), đôi khi có biến thể Karashi Ginrin (vảy ánh kim) hoặc Doitsu Karashi (da trơn không vảy). Karashi được lai tạo từ Kigoi và Chagoi, nổi tiếng với khả năng phát triển kích thước khổng lồ, có thể đạt tới 80–100cm, và được ví như “người khổng lồ hiền lành” trong hồ Koi.\\nMột Karashi đẹp phải có màu vàng đồng đều, tươi sáng, không loang lổ; thân hình to khỏe, khung xương lớn, dáng thuôn dài cân đối; vảy đều và sáng bóng. Ngoài vẻ đẹp đơn giản nhưng nổi bật, Karashi còn được yêu thích bởi tính cách thân thiện, dễ gần, thường nhanh chóng làm quen với người nuôi và tạo sự cân bằng cho cả đàn Koi. Chính sự kết hợp giữa màu sắc vàng rực rỡ, kích thước vượt trội và tính cách hiền hòa đã khiến Karashi trở thành một trong những giống Koi đặc biệt giá trị trong bộ sưu tập."),
            new Variety(null, "Benigoi", // 9
                    "Cá Koi Benigoi là giống cá đơn sắc thuộc nhóm Kawarimono, nổi bật với toàn thân màu đỏ đậm rực rỡ, vảy óng ánh đỏ và vây ngực đỏ hoàn toàn, không có chút màu trắng nào. Thân cá mập cân đối, thuôn dài, đầu hơi gù, phần đầu và vai to rộng, tạo dáng khỏe mạnh và uy nghi.\\nMột Benigoi đẹp phải có màu đỏ đồng đều, sâu và sáng, không loang lổ; vảy đều, sáng bóng; thân hình chắc khỏe, dáng bơi thẳng và uyển chuyển. Đây là dòng Koi có thể phát triển kích thước lớn, đạt tới 70–90cm trong điều kiện nuôi dưỡng tốt, đồng thời mang tính cách thân thiện, dễ gần. Benigoi được yêu thích bởi sự đơn giản nhưng nổi bật, màu đỏ tượng trưng cho may mắn, thịnh vượng và sức sống, khiến giống cá này trở thành điểm nhấn sang trọng và giá trị cao trong bộ sưu tập Koi."),
            new Variety(null, "Chagoi", // 10
                    "Cá Koi Chagoi là giống cá đơn sắc thuộc nhóm Kawarimono, nổi bật với màu nâu đất, xanh xám hoặc lục nhạt, mang vẻ đẹp giản dị nhưng mạnh mẽ. Đây là dòng Wagoi (có vảy), thường có hiệu ứng viền sáng quanh vảy (fukurin) tạo cảm giác lưới tự nhiên. Thân cá to khỏe, vai rộng, bụng tròn, cặp râu dài và cứng, vây ngực, vây lưng và đuôi dày chắc chắn.\\nMột Chagoi đẹp phải có màu sắc đồng đều, sâu và rõ, không loang lổ; thân hình cân đối, khỏe mạnh; dáng bơi thẳng, uyển chuyển. Đây là dòng Koi phát triển nhanh nhất, có thể đạt kích thước khổng lồ từ 80–100cm, đồng thời nổi tiếng với tính cách hiền hòa, thân thiện, thường là cá đầu tiên ăn từ tay người nuôi và giúp các dòng Koi khác trở nên dạn dĩ hơn.\\nChagoi được yêu thích bởi sự đơn giản nhưng giá trị, mang ý nghĩa tượng trưng cho tình bạn, sự gắn kết và mối quan hệ bền chặt. Chính sự kết hợp giữa kích thước vượt trội, tính cách hiền hòa và màu sắc mộc mạc khiến Chagoi trở thành một trong những giống Koi đặc biệt quan trọng trong bộ sưu tập."),
            new Variety(null, "Hikari Muji", // 11
                    "Cá Koi Hikari Muji (hay Hikari Mono) là dòng cá đơn sắc đặc trưng với lớp vảy kim loại ánh kim rực rỡ, toàn thân chỉ có một màu duy nhất. Đây là nhóm Ogon trong hệ Kawarimono, nổi bật bởi sự óng ánh của vảy và màu sắc thuần khiết, tạo nên vẻ đẹp sang trọng và mạnh mẽ. Vây cá cùng màu với thân, đồng đều và sáng bóng, làm tăng thêm sự hài hòa tổng thể.\\nMột Hikari Muji đẹp phải có màu sắc đồng đều, ánh kim rõ rệt, vảy đều và sáng, thân hình cân đối, khỏe mạnh. Dòng này có nhiều biến thể theo màu sắc: Platinum Ogon (trắng ánh kim), Nezu Ogon (đen ánh kim), Yamabuki Ogon (vàng ánh kim), Hi Ogon (đỏ ánh kim), Orenji Ogon (cam ánh kim), và Mukashi Ogon (xám bạc ánh kim).\\nHikari Muji được yêu thích bởi sự đơn giản nhưng nổi bật, mang lại điểm nhấn mạnh mẽ trong hồ Koi. Với ánh kim lấp lánh và màu sắc thuần khiết, chúng tượng trưng cho sự thịnh vượng, sang trọng và quyền lực, trở thành một trong những giống Koi giá trị cao trong bộ sưu tập."),
            new Variety(null, "Asagi", // 12
                    "Cá Koi Asagi là một trong những giống cá cổ điển nhất trong thế giới Koi, nổi bật với lớp vảy hình quả trám trên lưng tạo thành mạng lưới đều đặn màu xanh bạc trên nền trắng. Đầu cá trắng sáng thuần khiết, trong khi vây, bụng, hông và má thường điểm xuyết thêm sắc đỏ, vàng hoặc kem, lan ra cả mép miệng. Lớp lưới trên lưng phải đều, không bị đứt đoạn, đây là yếu tố quan trọng để đánh giá Asagi đẹp.\\nCác biến thể chính của Asagi gồm: Konjo Asagi với màu xanh chàm đậm gần như đen, Narumi Asagi với màu xanh lam sáng dịu cùng hiệu ứng viền trắng quanh vảy (fukurin), Mizo Asagi với màu xanh nước biển cực nhạt ngả sang xám bạc, và Ginrin Asagi với lớp ánh kim lấp lánh trên vảy lưng phản chiếu ánh sáng rực rỡ.\\nMột Asagi đẹp phải có màu xanh đồng đều, lớp lưới rõ ràng, đầu trắng sạch sẽ không tỳ vết, và sắc đỏ hoặc vàng ở bụng, vây, má phân bổ hài hòa. Thân hình to khỏe, dáng thuôn dài, bơi uyển chuyển, tạo cảm giác thanh thoát nhưng mạnh mẽ. Asagi được xem là biểu tượng của sự cân bằng và hài hòa, mang lại vẻ đẹp cổ điển, tinh tế và giá trị cao trong bộ sưu tập Koi."),
            new Variety(null, "Shusui", // 13
                    "Cá Koi Shusui là thế hệ lai từ Asagi, thuộc nhóm da trơn (Doitsu), nổi bật với hai hàng vảy xanh-đen đối xứng chạy thẳng dọc sống lưng đến tận đuôi. Thân cá sáng, hai bên hông bụng có mảng đỏ hoặc cam rực rỡ kéo dài đến đuôi, ranh giới rõ nét, tạo nên vẻ đẹp thanh thoát và mạnh mẽ.\\nMột Shusui đẹp phải có hàng vảy lưng đều, thẳng hàng, bóng đẹp, không bị đứt đoạn; màu đỏ/cam đồng đều, sắc nét, không loang lổ; thân hình to khỏe, dáng thuôn dài, bơi uyển chuyển. Đây là dòng Koi có thể đạt kích thước lớn (75–90cm), tuổi thọ cao, và được xem là một trong những giống Doitsu Koi đầu tiên, mang giá trị lịch sử đặc biệt.\\nCác biến thể chính gồm: Shusui thường với thân trắng chủ đạo và dải đỏ nhỏ ở hông; Hi Shusui với mảng đỏ chiếm diện tích lớn hơn, nổi bật hơn; ngoài ra còn có Ginrin Shusui (vảy lưng ánh kim lấp lánh) và Mizu Shusui (màu xanh nước biển nhạt gần như xám bạc).\\nShusui được yêu thích bởi sự kết hợp hài hòa giữa ba màu đen – đỏ – trắng (đôi khi xanh lam), tượng trưng cho sự cân bằng và may mắn, khiến giống cá này trở thành điểm nhấn độc đáo trong bộ sưu tập Koi."),
            new Variety(null, "Goshiki", // 14
                    "Cá Koi Goshiki là giống cá lai giữa Kohaku và Asagi, thuộc nhánh Goromo, nổi bật với sự kết hợp màu sắc phức tạp và độc đáo. Nền da trắng sáng phủ lớp vảy dạng lưới xanh–đen, trên đó là các mảng đỏ rực rỡ đặc trưng của Kohaku. Khi thả vào nước lạnh, màu sắc của Goshiki thường tối hơn, tạo hiệu ứng thay đổi theo môi trường.\\nMột Goshiki đẹp phải có màu đỏ (Hi) đậm, sắc nét, không bị lẫn bởi lớp lưới; nền trắng sạch sẽ, không ngả vàng; lớp vảy lưới đều, rõ ràng, không loang lổ. Thân hình to khỏe, vai rộng, dáng bơi thẳng và uyển chuyển. Đây là dòng Koi có thể đạt kích thước lớn (60–90cm) và tuổi thọ cao.\\nCác biến thể chính gồm: Goshiki truyền thống với nền trắng, lưới xanh–đen và mảng đỏ Kohaku; Doitsu Goshiki (dòng da trơn, chỉ có hàng vảy lớn chạy dọc lưng); và Goshiki hiện đại với nền sáng hơn, lưới tinh tế, mảng đỏ rõ ràng, ít bị “bẩn” bởi sashi.\\nGoshiki được yêu thích bởi sự hòa quyện của năm màu sắc: trắng, đỏ, xanh lam, xanh chàm và đen, tượng trưng cho sự cân bằng, sang trọng và may mắn. Chính sự phức tạp và độc đáo này khiến Goshiki trở thành một trong những giống Koi giá trị cao trong bộ sưu tập."),
            new Variety(null, "Hikarimoyo", // 15
                    "Cá Koi Hikarimoyo là dòng Koi ánh kim đa sắc, nổi bật với lớp vảy kim loại và da ánh kim óng ánh, kết hợp từ hai đến nhiều màu sắc cùng hoa văn ngẫu nhiên. Đây là nhóm Koi mang vẻ đẹp rực rỡ, sang trọng, thường được xem là điểm nhấn trong hồ Koi nhờ sự đa dạng màu sắc và ánh sáng phản chiếu mạnh mẽ.\\nMột Hikarimoyo đẹp phải có lớp vảy ánh kim đồng đều, sáng bóng, màu sắc rõ ràng, hoa văn phân bố hài hòa; thân hình cân đối, khỏe mạnh, dáng bơi uyển chuyển.\\nCác biến thể chính gồm: Hariwake với hoa văn màu cam hoặc vàng trên nền ánh kim. Yamato Nishiki với Hoa văn đỏ kết hợp đốm đen, tạo sự tương phản mạnh. Kujaku với Nền bạch kim với vảy hình chữ nhật, hoa văn màu cam hoặc đỏ. Kikusui với Hoa văn đỏ, thuộc dòng da trơn Doitsu (không vảy), mang vẻ đẹp thanh thoát.\\nHikarimoyo được yêu thích bởi sự đa dạng và rực rỡ, tượng trưng cho sự thịnh vượng, may mắn và quyền lực. Chính sự kết hợp giữa ánh kim lấp lánh và hoa văn đa sắc khiến Hikarimoyo trở thành một trong những giống Koi giá trị cao, thường được lựa chọn để làm nổi bật hồ Koi."),
            new Variety(null, "Kawarimono", // 16
                    "Cá Koi Kawarimono là nhóm phân loại rất lớn dành cho tất cả các giống Koi phi kim loại không nằm trong các nhóm ánh kim (Hikari) hay hoa văn truyền thống. Đây là dòng đa dạng nhất, bao gồm nhiều biến thể đơn sắc và các kiểu hoa văn đặc biệt, mang vẻ đẹp mộc mạc nhưng mạnh mẽ.\\nMột Kawarimono đẹp thường có thân hình vạm vỡ, dài, đầu to thuôn dài, xương vây ngực dày chắc; da mờ (matte) nhưng bóng mịn tự nhiên, phản ánh màu sắc sâu và đặc; vảy đa dạng, có thể là vảy lưới thô hoặc vảy kim cương; hoa văn trải dài từ đơn sắc hoàn toàn đến các mô hình phức tạp, thậm chí có dòng tự biến đổi theo nhiệt độ môi trường.\\nCác phân loại chính gồm: Koi đơn sắc (Single Colored) như Magoi, Chagoi, Soragoi, Kigoi, Benigoi. Magoi (Hắc Long cổ đại) với thân đen xám hoặc nâu đất tối, vảy lưới thô, kích thước cực đại, mang tính hoang dã. Karasugoi với toàn thân đen tuyền, sâu hơn Magoi, thân mập mạp. Hajiro, Hageshiro, Yotsujiro là các biến thể đen với điểm trắng ở vây hoặc đầu, rất hiếm. Matsubagoi là cá đơn sắc (vàng, đỏ, trắng) nhưng mỗi vảy có tâm đen tạo hiệu ứng quả thông (Aka Matsuba, Ki Matsuba). Koi chuyển màu như Ochiba Shigure với họa tiết lá thu rơi (nâu/cam trên nền xám bạc); Midorigoi cực hiếm với màu xanh lục nhạt hoặc xanh lá cây, thường thuộc dòng da trơn Doitsu.\\nKawarimono được yêu thích bởi sự đa dạng, kích thước vượt trội và tính cách thân thiện. Trong phong thủy, nhóm này tượng trưng cho sự bền bỉ, sức mạnh và khả năng thích nghi, khiến chúng trở thành nền tảng quan trọng trong bất kỳ bộ sưu tập Koi nào."));
}
